### ISSUE TITLE
Reduce HTML to smaller samples

### ISSUE THREAD

**Issue by BX326** [url2ref/url2ref#17]
Reduce HTML test data samples as described [here](https://github.com/url2ref/url2ref/pull/14#issuecomment-1855087052) in #14.

**Comment by philipwastakenwastaken** [comment]
Is this ready to be closed  since #14 has been merged?

**Comment by BX326** [comment]
Yes. It'll be closed automatically when dev is merged into main. Of course we could close it manually, but...
